### ISSUE TITLE
Update 3D viewer v2

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#1830]
Just tracking possible next features for the 3d-file viewer.

### Todo
- [x] Add controls.
- [ ] Add `gcode` loader.
- [x] Fix memory issues https://github.com/lbryio/lbry-desktop/issues/1863
- [x] Fix flow errors / warnings.

**Comment by alyssaoc** [comment]
@btzr-io can this be closed? should an issue for gcode be opened

**Comment by btzr-io** [comment]
@alyssaoc ok, you should ask  @jamesbiller if the app needs a `gcode` support.
