### ISSUE TITLE
Invitation Change and Micro-Tutorial

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-desktop#2165]
##Invitation Featured At Top Level With a CTA and Guidance

### Acceptance Criteria
1. Invitation Featured On Main Menu
2. Users prompted to invite friends on first run
3. A Yerbil tutorial the first time someone goes to the Invite screen

### Definition of Done
- [x]  The Invitation link is moved to the main menu in the app
- [x] A prompt asking users to invite their friends is part of first run
- [x] On the Invite screen, a Yerbil screen (similar to what is in Subscriptions) is there to instruct the user on why they should invite, and what they get for it
- [ ] Another prompt at a later date (if a week passes and they have not sent an invite) if they have not sent an invite to go send an invite at app startup
- [ ] A single claim button that shows total claimable amount, as opposed to clicking claim next to each invite. Still show the column with claimability status. See discussion in https://github.com/lbryio/internal-apis/issues/746

That fourth one could be changed based on what makes the most sense to complete this and ship it.

**Comment by seanyesmunt** [comment]
First version of this will be released without # 4

I think that's something we might want to extend in the future with more options. Not sure of the best way to do that right now.

**Comment by seanyesmunt** [comment]
closing this in favor of #2236

**Comment by tzarebczan** [comment]
Reopening to track completion of new reward claiming mechanism.
