### ISSUE TITLE
0.36 SDK changes + support

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2388]
## The Issue
Lots of these will be in redux, but creating issue here for awareness. 

- [ ] use stream update instead of publish when editing claims. Need to pass the claim id. Otherwise publish doesn't allow certain things like clearing channels/fees/locations/tags, etc. 

- [ ] Set/handle/show release time https://github.com/lbryio/lbry-desktop/issues/2328

- [ ] publish process needs to support mature content with the new tags https://github.com/lbryio/lbry-desktop/issues/2328

- [ ] file page/tiles need to support mature content tags https://github.com/lbryio/lbry-desktop/issues/2328

- [x] add --blocking call to claim abandon (this will ensure it finishes before we refresh, not default anymore)

- [x] may need to call channel / stream abandon based on type

- [x] claim list mine > claim list

- [x] claim tip > support create with --tip flag

- [ ] publish/edits - need to pass --clear_channel when setting anonymous channel, --clear_tags if removing any tags (or just add new tags without clearing), pass --clear_fee if removing the fee. 

- [x] channel new > channel create

- [x] claim list by channel > claim search with --channel_id paramater 
- I edited the call to use claim id, but the return doesn't have publisher data yet in 0.35.

- [x] thumbnail > thumbnail_url

- [x] content_type > media_type -changed this in a couple places...think it should cover it,. but didn't rename content type to media type everywhere (we u

- [ ] nsfw is gone, now set as a tag: see https://github.com/lbryio/lbry-desktop/issues/2328

- [ ] we now have the filename in metadata, useful to show? 

- [ ] language must be in RFC 5646 format.

- [x] value.stream.metadata > value.stream (everything is first class).

- [x] language > languages in metadata:
`"language": "en",` 
now: 
```
"languages": [
            "en"
          ],
```
- [x] don't pass publish params into metadata directly, use json

- [x] rename licenseUrl to license_url? Should no longer be passed into metadata.

Channel metadata
```

        Create a new channel by generating a channel private key and establishing an '@' prefixed claim.

        Usage:
            channel_create (<name> | --name=<name>) (<bid> | --bid=<bid>)
                           [--allow_duplicate_name=<allow_duplicate_name>]
                           [--title=<title>] [--description=<description>] [--email=<email>] [--featured=<featured>...]
                           [--tags=<tags>...] [--languages=<languages>...] [--locations=<locations>...]
                           [--website_url=<website_url>] [--thumbnail_url=<thumbnail_url>] [--cover_url=<cover_url>]
                           [--account_id=<account_id>] [--claim_address=<claim_address>] [--preview]

        Options:
            --name=<name>                  : (str) name of the channel prefixed with '@'
        --allow_duplicate_name=<allow_duplicate_name> : (bool) create new channel even if one already exists with
                                              given name. default: false.
            --bid=<bid>                    : (decimal) amount to back the claim
            --title=<title>                : (str) title of the publication
            --description=<description>    : (str) description of the publication
            --featured=<featured>          : (list) claim_ids of featured content in channel
            --tags=<tags>                  : (list) content tags
            --languages=<languages>        : (list) languages used by the channel,
                                                    using RFC 5646 format, eg:
                                                    for English `--languages=en`
                                                    for Spanish (Spain) `--languages=es-ES`
                                                    for Spanish (Mexican) `--languages=es-MX`
                                                    for Chinese (Simplified) `--languages=zh-Hans`
                                                    for Chinese (Traditional) `--languages=zh-Hant`
            --locations=<locations>        : (list) locations of the channel, consisting of 2 letter
                                                    `country` code and a `state`, `city` and a postal
                                                    `code` along with a `latitude` and `longitude`.
                                                    for JSON RPC: pass a dictionary with aforementioned
                                                        attributes as keys, eg:
                                                        ...
                                                        "locations": [{'country': 'US', 'state': 'NH'}]
                                                        ...
                                                    for command line: pass a colon delimited list
                                                        with values in the following order:

                                                          "COUNTRY:STATE:CITY:CODE:LATITUDE:LONGITUDE"

                                                        making sure to include colon for blank values, for
                                                        example to provide only the city:

                                                          ... --locations="::Manchester"

                                                        with all values set:

                                                 ... --locations="US:NH:Manchester:03101:42.990605:-71.460989"

                                                        optionally, you can just pass the "LATITUDE:LONGITUDE":

                                                          ... --locations="42.990605:-71.460989"

                                                        finally, you can also pass JSON string of dictionary
                                                        on the command line as you would via JSON RPC

                                                          ... --locations="{'country': 'US', 'state': 'NH'}"

            --email=<email>                : (str) email of channel owner
            --website_url=<website_url>    : (str) website url
            --thumbnail_url=<thumbnail_url>: (str) thumbnail url
            --cover_url=<cover_url>        : (str) url of cover image
            --account_id=<account_id>      : (str) id of the account to store channel
            --claim_address=<claim_address>: (str) address where the channel is sent to, if not specified
                                                   it will be determined automatically from the account
            --preview                      : (bool) do not broadcast the transaction

        Returns: {Transaction}
```

Channel sample: 
```    {
    "address": "bVyKHLxRHnjPKW4C4GUCQz67ynGZSfveZ1",
    "amount": "0.001",
    "claim_id": "04c91cf3dd1dfcb4414efc3eca24dc449fc28d4b",
    "claim_op": "create",
    "confirmations": 2,
    "height": 556665,
    "is_change": false,
    "is_mine": true,
    "name": "@NewMetadataChannel",
    "nout": 0,
    "permanent_url": "lbry://@NewMetadataChannel#04c91cf3dd1dfcb4414efc3eca24dc449fc28d4b",
    "txid": "b8f0eb451f648d360204efdc26173de33a8b7cbe0b66db21f84def2039868f45",
    "type": "claim",
    "value": {
      "cover": {
        "url": "https://spee.ch/5/tom-banner.jpg"
      },
      "description": "My Channel Description",
      "email": "tom@lbry.com",
      "featured": [
        "cda25338628bada976a78e7d04367ca075bde397"
      ],
      "languages": [
        "en",
        "es"
      ],
      "locations": [
        {
          "latitude": 429906050,
          "longitude": -714609890
        },
        {
          "city": "Manchester"
        }
      ],
      "public_key": "3056301006072a8648ce3d020106052b8104000a034200042030108c1670b7c204c8a30643e8779699978d8aa6556de154fb231bfc72c369a48c4c97f71de9a3dc5afa7ad020231c3051e933b5598816434d8680de21d6b1",
      "tags": [
        "tag1 chan",
        "tag2 chan"
      ],
      "thumbnail": {
        "url": "https://spee.ch/4/tom-z.jpg"
      },
      "title": "My Channel Title",
      "website_url": "lbry.com"
    },
    "value_type": "channel"
  },
```
Claim metadata:
```

        Create or update a stream claim at a given name (use 'stream create/update' for more control).

        Usage:
            publish (<name> | --name=<name>) [--bid=<bid>] [--file_path=<file_path>]
                    [--tags=<tags>...] [--clear_tags]
                    [--languages=<languages>...] [--clear_languages]
                    [--locations=<locations>...] [--clear_locations]
                    [--fee_currency=<fee_currency>] [--fee_amount=<fee_amount>] [--fee_address=<fee_address>]
                    [--title=<title>] [--description=<description>] [--author=<author>] [--language=<language>]
                    [--license=<license>] [--license_url=<license_url>] [--thumbnail_url=<thumbnail_url>]
                    [--release_time=<release_time>] [--width=<width>] [--height=<height>] [--duration=<duration>]
                    [--channel_id=<channel_id>] [--channel_name=<channel_name>]
                    [--channel_account_id=<channel_account_id>...]
                    [--account_id=<account_id>] [--claim_address=<claim_address>] [--preview]

        Options:
            --name=<name>                  : (str) name of the content (can only consist of a-z A-Z 0-9 and -(dash))
            --bid=<bid>                    : (decimal) amount to back the claim
            --file_path=<file_path>        : (str) path to file to be associated with name.
            --fee_currency=<fee_currency>  : (string) specify fee currency
            --fee_amount=<fee_amount>      : (decimal) content download fee
            --fee_address=<fee_address>    : (str) address where to send fee payments, will use
                                                   value from --claim_address if not provided
            --title=<title>                : (str) title of the publication
            --description=<description>    : (str) description of the publication
            --author=<author>              : (str) author of the publication. The usage for this field is not
                                             the same as for channels. The author field is used to credit an author
                                             who is not the publisher and is not represented by the channel. For
                                             example, a pdf file of 'The Odyssey' has an author of 'Homer' but may
                                             by published to a channel such as '@classics', or to no channel at all
            --clear_tags                   : (bool) clear existing tags (prior to adding new ones)
            --tags=<tags>                  : (list) add content tags
            --clear_languages              : (bool) clear existing languages (prior to adding new ones)
            --languages=<languages>        : (list) languages used by the channel,
                                                    using RFC 5646 format, eg:
                                                    for English `--languages=en`
                                                    for Spanish (Spain) `--languages=es-ES`
                                                    for Spanish (Mexican) `--languages=es-MX`
                                                    for Chinese (Simplified) `--languages=zh-Hans`
                                                    for Chinese (Traditional) `--languages=zh-Hant`
            --clear_locations              : (bool) clear existing locations (prior to adding new ones)
            --locations=<locations>        : (list) locations relevant to the stream, consisting of 2 letter
                                                    `country` code and a `state`, `city` and a postal
                                                    `code` along with a `latitude` and `longitude`.
                                                    for JSON RPC: pass a dictionary with aforementioned
                                                        attributes as keys, eg:
                                                        ...
                                                        "locations": [{'country': 'US', 'state': 'NH'}]
                                                        ...
                                                    for command line: pass a colon delimited list
                                                        with values in the following order:

                                                          "COUNTRY:STATE:CITY:CODE:LATITUDE:LONGITUDE"

                                                        making sure to include colon for blank values, for
                                                        example to provide only the city:

                                                          ... --locations="::Manchester"

                                                        with all values set:

                                                 ... --locations="US:NH:Manchester:03101:42.990605:-71.460989"

                                                        optionally, you can just pass the "LATITUDE:LONGITUDE":

                                                          ... --locations="42.990605:-71.460989"

                                                        finally, you can also pass JSON string of dictionary
                                                        on the command line as you would via JSON RPC

                                                          ... --locations="{'country': 'US', 'state': 'NH'}"

            --license=<license>            : (str) publication license
            --license_url=<license_url>    : (str) publication license url
            --thumbnail_url=<thumbnail_url>: (str) thumbnail url
            --release_time=<release_time>  : (int) original public release of content, seconds since UNIX epoch
            --width=<width>                : (int) image/video width, automatically calculated from media file
            --height=<height>              : (int) image/video height, automatically calculated from media file
            --duration=<duration>          : (int) audio/video duration in seconds, automatically calculated
            --channel_id=<channel_id>      : (str) claim id of the publisher channel
            --channel_name=<channel_name>  : (str) name of publisher channel
          --channel_account_id=<channel_id>: (str) one or more account ids for accounts to look in
                                                   for channel certificates, defaults to all accounts.
            --account_id=<account_id>      : (str) account to use for funding the transaction
            --claim_address=<claim_address>: (str) address where the claim is sent to, if not specified
                                                   it will be determined automatically from the account
            --preview                      : (bool) do not broadcast the transaction

        Returns: {Transaction}
```

Claim sample:

```
  {
    "address": "bLzLCM4fPya9kUbXrme1Gjf6aMM9rpon38",
    "amount": "0.0001",
    "claim_id": "3ecd483fa98f93024de36648fa2786f6b2d244f6",
    "claim_op": "create",
    "confirmations": 2,
    "height": 556667,
    "is_change": false,
    "is_channel_signature_valid": true,
    "is_mine": true,
    "name": "NewMetadataPub01",
    "nout": 0,
    "permanent_url": "lbry://NewMetadataPub01#3ecd483fa98f93024de36648fa2786f6b2d244f6",
    "signing_channel": {
      "claim_id": "04c91cf3dd1dfcb4414efc3eca24dc449fc28d4b",
      "name": "@NewMetadataChannel",
      "value": {
        "cover": {
          "url": "https://spee.ch/5/tom-banner.jpg"
        },
        "description": "My Channel Description",
        "email": "tom@lbry.com",
        "featured": [
          "cda25338628bada976a78e7d04367ca075bde397"
        ],
        "languages": [
          "en",
          "es"
        ],
        "locations": [
          {
            "latitude": 429906050,
            "longitude": -714609890
          },
          {
            "city": "Manchester"
          }
        ],
        "public_key": "3056301006072a8648ce3d020106052b8104000a034200042030108c1670b7c204c8a30643e8779699978d8aa6556de154fb231bfc72c369a48c4c97f71de9a3dc5afa7ad020231c3051e933b5598816434d8680de21d6b1",
        "tags": [
          "tag1 chan",
          "tag2 chan"
        ],
        "thumbnail": {
          "url": "https://spee.ch/4/tom-z.jpg"
        },
        "title": "My Channel Title",
        "website_url": "lbry.com"
      }
    },
    "txid": "369264300c06247cb1d101e03ba778b9ec6a05a85094073e20c89df2915f5ec4",
    "type": "claim",
    "value": {
      "author": "Author Test",
      "description": "My Claim Description",
      "fee": {
        "address": "bLzLCM4fPya9kUbXrme1Gjf6aMM9rpon38",
        "amount": 1.0,
        "currency": "LBC"
      },
      "languages": [
        "en",
        "es"
      ],
      "license": "All Rights Reserved Test",
      "license_url": "https://www.tom.com",
      "locations": [
        {
          "latitude": 429906050,
          "longitude": -714609890
        },
        {
          "city": "Manchester"
        }
      ],
      "release_time": "1555951910",
      "source": {
        "hash": "8480f4a320b4cff22e060fc3691a215bbf11d1e9af580b36861ea425d525b8b3",
        "media_type": "video/mp4",
        "name": "TQUS44N6e6moJzrHJc8lQ6OC_3.mp4",
        "sd_hash": "14503ca14b52eed15be1c7fd0dc14afa1e30a146b47b55de50e87c6aaa261ce88e6b07a986a212386face73c8cbf7083",
        "size": "13474499"
      },
      "stream_type": "video",
      "tags": [
        "tag1",
        "tag2"
      ],
      "thumbnail": {
        "url": "https://spee.ch/4/tom-z.jpg"
      },
      "title": "Test Title",
      "video": {
        "duration": 10,
        "height": 360,
        "width": 480
      }
    },
    "value_type": "stream"
  },
```
