### ISSUE TITLE
outstanding issues after recent optimizations / lbry.tv changes / 0.36

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2431]
## The Issue
- [x] https://github.com/lbryio/lbry-desktop/pull/2459 doesn't seem to work. We can probably safely pass this on both new publishes and edits. 
- [x] cannot set a fee via publish screen - don't see the param passed to the publish call. 
- [x] preview mode in MD editor on publish page doesn't seem to work..description goes blank. Both in light and dark mode. Can we turn off the spell checker too? 

- [x] tip unlock icon is not showing. Also, if a tip comes in and you click the refresh button, it didn't used to show the tip icon in 0.31.1..but if you left the screen and came back, it would. Would be nice to kill 2 birds with 1 stone here. **claim list no longer return supports, support list does instead**
 
- [x] don't pass 'null' on  publish for fields like license_url, this will fail on the SDK currently. 
- [x] 37 removes block show: https://github.com/lbryio/lbry-desktop/issues/2448
- [x] key warning on fixes branch (Sean aware)
```react.development.js:188 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `_default`. See https://fb.me/react-warning-keys for more information.
    in span (created by _default)
    in _default (created by _default)
```
- [x] search  "lbry ladies" 
```
TypeError: Cannot read property 'certificateId' of undefined
    at downloadResultsFromQuery.length.downloadResultsFromQuery.map.fileInfo (ui.js:40234)
    at Array.map (<anonymous>)
    at reselect.createSelector (ui.js:40226)
    at ui.js:89982
    at ui.js:89942
    at ui.js:89996
    at ui.js:89942
    at Function.select [as mapToProps] (ui.js:99677)
    at mapToPropsProxy (ui.js:73189)
    at Function.detectFactoryAndVerify (ui.js:73198)
error @ ui.js:67242
ui.js:69156 Uncaught TypeError: Cannot read property 'certificateId' of undefined
    at downloadResultsFromQuery.length.downloadResultsFromQuery.map.fileInfo (ui.js:40234)
```
- [x] grey out send button on tip screen if amount not entered. 
- [x] a) fix claim search to use uri in redux like: https://github.com/lbryio/lbry-desktop/commit/b6529ff58c3062c9706c733af101a62de82dea8f#diff-7a5fcf2fcba9d28754e0769cdc66affaR311

- [x] b)another place we need the title selector:
```
publish.js:277 Uncaught (in promise) TypeError: Cannot read property 'title' of undefined
    at claims.forEach.claim (publish.js:277)
    at Array.forEach (<anonymous>)
    at lbry_redux__WEBPACK_IMPORTED_MODULE_2__.Lbry.claim_list.then.claims (publish.js:270)
claims.forEach.claim    @    publish.js:277
```
and
`const { title } = value.stream;`

- [x] c) add --replace option to publish calls so that all field values are replaced with what we pass (we pass all currently). https://github.com/lbryio/lbry/releases/tag/v0.37.0rc3

- [ ] d) address https://github.com/lbryio/lbry-desktop/issues/2419 (spacebar doesn't pause)
- [x] e) after verifying a phone number successfully, the input phone number screen reappears. It then disappears when the first reward is claimed successfully. It should just disappear right away - sometimes the reward may not be claimable right away (if the account requires a 2nd level of manual approval). 
- [x] f) cannot abandon claim if lbry file is deleted. You can click the "abandon url" option when going through the file page, but it doesn't call abandon. If the file is downloaded, it does abandon it. (old 0.31 bug).
- [x] g) fix audio player or revert to old one (Shawn K's changes were not working to control volume/seek).
- [x] h) waiting for blob on open source games like lbry://wubwubwub#e5172191477067f476dc3f445b13df06a83b8048. Works fine when you leave/come back. Same on PDF: lbry://pdf#a9a162083588817209c2d07903371aedd6d9c082
- [x] i) open.lbry.com urls don't work when app is closed. 

- [x] j) don't show "The publisher has chosen to charge LBC to view this content. Your balance is currently to low to view it. Checkout the rewards page or send more LBC to your wallet." when the content is already in your downloads/purchased. 
- [x] k) on lbry://py#1499b64a686aa1f34dbbe8e1cc84292c4e81379d ran into https://github.com/lbryio/lbry-desktop/issues/2386
- [ ] l) right click error on web version
  - This can be it's own issue
```
ui.js:12 Uncaught ReferenceError: clipboard is not defined
    at a (ui.js:12)
    at l (ui.js:12)
...
```
- [x] lost video player controls in dev:web mode on sdk-changes branch 

- [x] publish button changes to green gradient color when on the publish page, expected? 

- [x] loading vanity url for channel fails, i.e. @jiggytom. ```"Must specify either name, claim_id, or txid:nout."``` in ```export function doFetchClaimsByChannel(uri, page = 1, pageSize = PAGE_SIZE) {```
- [x] on SDK changes branch - subscription page showed up blank after adding a single channel.  Might be related to https://github.com/lbryio/lbry-desktop/issues/2398

- [x] m) waiting for blob on video files. Works after it completes, but uses new video player. 

- [x] n) we should fix this up as well: https://github.com/lbryio/lbry-desktop/issues/2434 / https://github.com/lbryio/lbry-desktop/issues/2398 / https://github.com/lbryio/lbry-desktop/issues/2391 / https://github.com/lbryio/lbry-desktop/issues/2390 / https://github.com/lbryio/lbry-desktop/issues/2386 

- [x] o) reward list called twice on startup
- [x] p) If you leave the publishes page and come back, the claim takes about 30 seconds to confirm on screen even though it's already confirmed on the blockchain.
  - This can be opened as a separate issue. It is not a blocker
- [x] q) duplicate notifications when publish completes (if you leave the publish page, come back)

- [x] seeing this error on subscriptions page after Jeremy's fix
```
Uncaught (in promise) TypeError: Cannot read property 'fee' of undefined
    at o.slice.forEach.e (ui.js:12)
    at Array.forEach (<anonymous>)
    at u.Lbry.claim_search.then.r (ui.js:12)
```

- [x] open.lbry.com urls like https://open.lbry.com/jiggytom don't go to the claim in app

- [x] edit claim does not re-populate publish data. Publish button goes green

- [x] entering `one&two` into the search bar shows `lbry://one` at the top when you go to the search page

- [x] screen stutters, displays black text very briefly on startup. 

- [x] make top left LBRY icon go back to explore page

- [x] file:///C:/static/img/placeholder.png does not load (no default thumbnail icon). 

- [x] grey out send button if tip > balance (or if balance is 0).

- [x] size of downloaded tiles not consistent with other pages

- [x] styling overlap
![image](https://user-images.githubusercontent.com/8120721/56439971-ec071300-62b5-11e9-8fcc-b97e493e1415.png)
- [x] make lbry URL easily copyable from file page (right now you get a hyperlink hand hover over) 

- [x] after deleting a file, you get a black loading screen in the player. 

- [x]  urls with bad characters, i.e. lbry://test&, cause green screen error.  
```
User(821949) Desktop Error: /C:/Program%20Files/LBRY/resources/app.asar/index.html

   TypeError: i is not a function
```
- [x] scrollbar appears in left pane + new content value is cut off when new content > 100 items

- [x] recheck https://github.com/lbryio/lbry-desktop/issues/2421 after links work.

- [x] font size different on transactions + overview page (tx list)

- [x] don't show balance warning on own content. Can't even open it.```The publisher has chosen to charge LBC to view this content. Your balance is currently to low to view it. Checkout the rewards page or send more LBC to your wallet.``` Even if they deleted the file, the payment will just go back into their own wallet. 

- [x] only URL encode twitter url, leave rest as is (currently the links fail to open to the content on spee.ch, and fail in some browsers due to bad characters)

- [x] scroll state is saved when it shouldn't in some cases (i.e. scrolling down/clicking related content)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jessopb** [comment]
"make lbry URL easily copyable from file page (right now you get a hyperlink hand hover over)"
What do you want to do with it?

**Comment by seanyesmunt** [comment]
@jessopb I'll work on that one

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-desktop/commit/87cab7d355448ceb58e7a2cda9103042b268221b should address subscriptions not working

**Comment by jessopb** [comment]
Ubuntu vm did not repro i) ; needs more context.

**Comment by seanyesmunt** [comment]
@jessopb Is that for the open.lbry link?

**Comment by tzarebczan** [comment]
I cleared this up with Jessop, he's able to reproduce now.

**Comment by jessopb** [comment]
Not seeing q): duplicate publish notifications. More repro info?

**Comment by tzarebczan** [comment]
@jessopb did you see any notification? It may be broke by (b)..let me try fixing that one locally to reproduce. But I think it had something to do with navigating away/back to the publish page.

**Comment by tzarebczan** [comment]
wooooo!
