### ISSUE TITLE
Trending/Discovery megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2542]
## The Issue

- [ ] BLOCKER: lots of trouble with infinite scroll - does not actually scroll to next page on lots of scenarios. Tags pages work fine, and so do Top, but New/Trending for tags/everyone have lots of trouble. Refreshing app results in wrong pages + double calls 
- [x] double? 
![image (3)](https://user-images.githubusercontent.com/8120721/61675286-b8c58d00-acc5-11e9-9bd5-8439ffc79e06.png)

- [x] new lines not rendering: lbry://2d1a#3  ```"description": "test\nnew\nlines\n\nwhatttt"``` and urls with lbry:// in them keep resolving in background (lbry://test-desc#9c35eed8e1c331f9f70691c479837982f70f0011) 

- [x] BLOCKER: when getting to end of infinite scroll list, it keeps refreshing/bugging out (nice find Jessob): Bug on fixes: set followed tags to only ["bubbles"], scroll down several times.
Infinite looping load/reload of last page of results - This happens when the search runs out of results. 

- [ ] BLOCKER? : publishes page won't show a timestamp until you go into the claim - because meta is not available for local claims. We need to resolve them all, or show the last updated time on publishes page. This means the date on claim may be different (we eventually want to show update date too).

- [x] BLOCKER?: infinite scroll doesn't work sometimes if the customize tags screen is injected. It works after dismissing it. 

- [x] BLOCKER: sticky side bar gets stuck / offset . It's also jumpy when scrolling

- [x] BLOCKER: Fix language or disable

- [x] BLOCKER? tag analytics: https://github.com/lbryio/lbry-desktop/issues/2618

- [x] BLOCKER: fix redux valid URI checking (message is correct on publish page, but redux doesn;t have the characters we want to block) 

- [ ] ~BLOCKER~: date disappears on published claims (appears briefly, and then poof!) 
![image (4)](https://user-images.githubusercontent.com/8120721/61307122-bf32a100-a7bb-11e9-87e7-facbb5ecd56c.png)

- [x] BLOCKER: 2 big issues: 1) if you click page 2 on a channel and then another channel or tag from side bar, it will show "no content". 2) If you click page 2 and then click back, it still shows page 2. 

- [x] BLOCKER: add change email link during verification process - this is the most common case users want to change their email (if it was incorrectly typed)
  - This is not related to the new discovery changes and should be its own issue. TZ: we should at least add the link, will open new issue for correct process. 

- [x] BLOCKER: only show suggested channels from preset list (don't show top subbed / top bid until we can handle channel blocking). 
- [x] BLOCKER? : invalid url shows like this on search results - do we want a tile with -"publish something here! "? 

![image](https://user-images.githubusercontent.com/8120721/60906934-50e36100-a246-11e9-97ac-4d2ce6053653.png)

- [x] BLOCKER: `Level up with LBRY - 0.33.0undefined` in tx history, undefined on every send/receive. This works sometimes, not others. 

- [x] BLOCKER?: auto download may not be working properly in last release, please double check, I saw recent content but it was not downloaded. 

- [x] BLOCKER: open.lbry.com url missing web hyperlink option. Also, think you want to use the short url there too

- [x] BLOCKER: can't remove mature tag from publishes edit page (keeps passing it to the api) 

- [x] BLOCKER: at least add channel handling to https://github.com/lbryio/lbry-desktop/issues/2463 since we share the open url which goes to lbry.tv. 

- [ ] BLOCKER?: (Sean thought this was done) -  allow setting of release date, or at least default it to publish time. On edits, it should keep the previous value (until we allow updating). 
- [x] BLOCKER?: publish page thumb option should default to upload tool.

- [x] fix formatting / display of exact url 
![image](https://user-images.githubusercontent.com/8120721/61403813-1d3ab380-a8a4-11e9-9839-1faa2cc5412e.png)

- [x] send in dark mode
![image](https://user-images.githubusercontent.com/8120721/61656090-f1497480-ac8d-11e9-827f-6ea8b4ed8313.png)

- [x] transactions page
![image](https://user-images.githubusercontent.com/8120721/61652085-3321ed00-ac85-11e9-84a2-6db73230c40c.png)

- [x] copy button 
![image (5)](https://user-images.githubusercontent.com/8120721/61646050-35307f80-ac76-11e9-8010-ab88518dc487.png)
- [x] upgrade
![image (6)](https://user-images.githubusercontent.com/8120721/61646054-38c40680-ac76-11e9-87ee-4a97a2407710.png)

- [x] appstatus error : ```User(1318657) Desktop Error: Uncaught error
app version: 0.34.0-rc.7
sdk version: 0.38.0
page: #/
TypeError: this.loadPromise.cancel is not a function
   at d.componentWillUnmount (file:///opt/LBRY/resources/app.asar/ui.js:191:191128)
   at ho (file:///opt/LBRY/resources/app.asar/ui.js:221:75762)
   at vo (file:///opt/LBRY/resources/app.asar/ui.js:221:77323)
   at zo (file:///opt/LBRY/resources/app.asar/ui.js:221:81576)
   at Vo (file:///opt/LBRY/resources/app.asar/ui.js:221:84893)
   at file:///opt/LBRY/resources/app.asar/ui.js:221:98269
   at Object.t.unstable_runWithPriority (file:///opt/LBRY/resources/app.asar/ui.js:229:3218)
   at As (file:///opt/LBRY/resources/app.asar/ui.js:221:98204)
   at Ns (file:///opt/LBRY/resources/app.asar/ui.js:221:97980)
   at Os (file:///opt/LBRY/resources/app.asar/ui.js:221:97325)```

- [ ] backup wallet to wallet page? Collapse button if someone does it? 
- [ ] editing a claim defaults to the price option with 0 value, instead of free (for free claims)

- [ ] multiple hover over channels sometimes: 
![hover](https://cdn.discordapp.com/attachments/377895389992321064/600468597365800963/unknown.png)

- [ ]  show short url for channel on publish / comments dropdowns. In case users have multiple channels with the same name after syncing, this will be easier to distinguish. 

- [ ] nice to have: my channels page 

- [ ] if we auto update the image/thumb on channel edit, we should do the same for title. 

- [ ] hover over channel info on comments.
- [ ] add infinite scroll/pagination to comments 

- [ ] remove scroll bar: 
![image](https://user-images.githubusercontent.com/8120721/60549732-b9d15300-9cf3-11e9-8438-ae0d0618bbd9.png)

- [ ] NICE TO HAVE: hover over description on buttons (publish, account, settings)

- [ ] add tags ui to channel page edit

- [ ] pending item in publishes shows twice sometimes (was able to repro this by leaving the publishes page, going to new, and then coming back)

- [ ] add sub count to publishers channel page
- [ ] f full screen shortcut does not work. Not clear how to get out of full screen. 
- [x] file size on file page info
- [x] move recent txs under send/receive on wallet page
- [x] show all button for tags? Hover over? 
- [x] send button should be green in dark mode on wallet page. Post button on comments too. 
- [x] profile image cut off (thanks Electron)
![prifle](https://media.discordapp.net/attachments/377895389992321064/597637575934476318/unknown.png)
- [x] ~BLOCKER~: first run messaging: https://github.com/lbryio/lbry-desktop/issues/2608
  - This is going to be moved into the next sprint - will create new issue
- [x] replace permanent url with canonical (tom will do)
- [x] BLOCKER: comments messaging: https://github.com/lbryio/lbry-desktop/issues/2600
- [x] save tags to subscription api (hacky, but works since we'll be going away from it) - we will save to analytics

- [x] BLOCKER: Somewhere we lost recommended channels. Add recommended channels if none subbed to? Tell them to customize and show there? 

- [x] BLOCKER: don't allow rewards page verification options if email verification is not completed (jeremy was able to send email, and go to rewards page. Should force you to verify first.

- [x] BLOCKER: when you infinite scroll a few times and then switch categories, it doens't reset the view anymore

- [x] BLOCKER: don't allow duplicate tags on publish screen (if you add dupes, it crashes when trying to remove)
- [x]  loading screens between pages. If you are on one page and go to another, you still see the old content before new content is loaded.

- [x] text lost in simple editor if you switch to advanced and go back. It's saved from advanced. 
- [x] ew
![image](https://user-images.githubusercontent.com/8120721/60302810-ce33db00-9902-11e9-9776-7f536e9e8145.png)

- [x] need border around inputs (price, license, channel, deposit, language, thumb url, etc). Title too? 

![image](https://user-images.githubusercontent.com/8120721/60304278-e73e8b00-9906-11e9-944e-41cf30456b11.png)

- [x] hovering over tag shows "remove tag" even though this goes to the tag page. 

- [x] following vs unfollow consistency on tags / channels (i.e. tags shows following, but channels show unfollow)
- [x] tags not repopulated on edit 
- [x] bid checking is not working - shows any amount. This is in meta>effective amount

- [x] where are mature options on publish? Should we put a checkbox right under tags that will add it? 

- [x] discovery options are lost when navigating to a video and going back (i..e from trending / you page, click video, go back) 

- [x] customize home page component - "suggested tags" label? 
- [x] license_url: null breaks publish, pass as blank instead. 
- [x] share modal - lost icons for twitter/fb 

- [x] pending shown at bottom (known sorting issue?)

- [x] cannot type spaces on pages if spacebar is not unbound 

- [x]  loose selected channel for comments when going back to home page

- [x] tags overflow on related...

- [x] make it clearer how edit following tags page - edit icon may not be clear enough 

- [x] long sub list cuts off at bottom of some pages:
![image](https://user-images.githubusercontent.com/8120721/60302483-fa9b2780-9901-11e9-8847-a1422ede6f69.png)
- [x] BLOCKER?: add NSFW tags to claim search if mature content is disabled: ```--not_tags=<not_tags>           : (list) find claims not containing any of these tags```

- [x] can't select text anywhere 

- [x] tip amount not greyed out if balance exceeded

- [x] filter on search page displaying strangely. 
![image](https://user-images.githubusercontent.com/8120721/59651691-c765d500-9158-11e9-8cc6-3d8a74676e13.png)

- [x] show accounts/settings menu on mobile (so at least users can see it / get message to download app)

- [x] make change email work, or hide for now.

- [x] hide blacklisted outpoints from trending/tags pages

- [x] Figure out how to handle featured content (mention it on rewards page?)

- [x] BLOCKER: allow tagging on publish screen

- [x] downloads only sort when I click oldest(reverses each time)

- [x] BLOCKER? Need to add content length on tiles, content length + size on file page

- [x] BLOCKER: pending items should be grayed out on publish

- [x] BLOCKER: can't scroll down to see all subs (need to add scroll bar back?
![image](https://user-images.githubusercontent.com/8120721/59279184-78d4aa00-8c31-11e9-87e3-cc1cf678359f.png)

- [x] latest content from subscriptions keeps trying to redownload on every restart + every 30min.

- [x] no txs view: 
![image](https://user-images.githubusercontent.com/8120721/60464198-e0bc5600-9c1b-11e9-885e-0d3681a9875e.png)
 
- [x] console error: ```ui.js:12 no icon found for  AlertCircle```

- [x] missing tip unlock button on tx page for tips

### Actual Behavior

Tell us what happens instead.

### Suggested Solutions

Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
We are moving to `Subscribe` and `Subscribed`, so we don't need the broken heart anymore
