### ISSUE TITLE
Epic - [More] Interactive Comments

### ISSUE THREAD

**Issue by osilkin98** [lbryio/lbry-desktop#3005]
- [x] Implement URL embedding in comments
- [x] Implement comment section on user channels
- [x] Add Comment Thumbnails
- [ ] Implement media uploading within comments (pasting an image from clipboard into comments - will require work on SDK side)
- [ ] Polish up the styling in the comment section 
- [ ] Push notifications for new comments (will require work on SDK side)

**Comment by btzr-io** [comment]
Some progress on the frontend side, markdown support for comments, still needs a few minor styles tweaks:

![comments-ui](https://user-images.githubusercontent.com/14793624/66710724-726b5180-ed3b-11e9-893e-dcda1f7a48ad.png)

**Comment by seanyesmunt** [comment]
@osilkin98 I don't think channel messaging should be bundled in with this, since it's not actually comments

**Comment by osilkin98** [comment]
Alright, I’ll make a separate issue for it.
