### ISSUE TITLE
Playlist fall out bugs + Epic

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6211]
Bugs:
- [x] If you go into a content page playlist view and then click back > forth (or navigate, you lose the playlist view. I.e. navigate to https://odysee.com/@playlistchantest:8/test3:c click their channel page, and then back. Or if on own list > view list, and back. 
- [ ] View List on content page should be "Edit list" if own claim? 
- [x] ordering buttons are reversed in operation 
- [x] there are reports of mixed up positions after a few operations (need to repro)

- [x] many users are clicking done after typing, and not the +. Maybe disable done if something is typed? Prompt that changes won't be saved? 
![image](https://user-images.githubusercontent.com/8120721/121571603-3e08d680-c9f1-11eb-816e-9e60ac72e2e9.png)

Minor stuff:
- [x] improve spacing: 
![image](https://user-images.githubusercontent.com/8120721/121571385-f2562d00-c9f0-11eb-98e8-8b1233b5c066.png)
- [x] improve alignment: 
![image](https://user-images.githubusercontent.com/8120721/121571910-9b048c80-c9f1-11eb-9dd7-31c940467055.png)

**Comment by lyoshenka** [comment]
scrollbar buttons visible even though there's no scrolling to do 

![image](https://user-images.githubusercontent.com/362784/121588202-a496f000-ca03-11eb-9b79-c147bfed9dd7.png)

**Comment by lyoshenka** [comment]
a bit of playlist feedback (this is from the perspective of clicking +Save under a video)

- making a new playlist and adding the current video to it was super smooth
- it did not say anywhere in the process that this will cost me lbc. 
- i thought making playlists was a two-step process where you have to commit the list later. did that change? if not, i wasn't told about it in the flow
- since this is a new feature, there's not explanation about it. what do lists do? how do i see my lists or play them? etc

**Comment by saltrafael** [comment]
feedback: maybe add each list to the expanded sidebar like followed channels and tags?

![](https://i.postimg.cc/pV5XFV9f/image.png) ![](https://i.postimg.cc/QNcZDF9y/image.png)

youtube example:

![](https://i.postimg.cc/brhMrRDF/image.png) ![](https://i.postimg.cc/PJJDmgwL/image.png)

**Comment by tzarebczan** [comment]
Will file that as as separate issue, thank you!
