### ISSUE TITLE
Feature Request: Bookmarking / Watch later lists

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#622]
_Edit by Liam:_ **Note to contributors** -- feel free to tackle this! But keep in mind that this needs to be implemented well and integrated well into our design and current redesign efforts. If you want to work on this, I recommend talking to either me or @seanyesmunt.

 

## The Issue
I've seen this feature requested or talked about a couple times (I think someone was even working on a proof of concept) so I wanted to track it via an issue here. 

The bookmarking feature would allow the user to maintain one or more lists to which users can save claims/channels to. Claim and channel pages would require an "Add to Bookmarks" button with a dropdown the ability to create a new list or add to existing one. 

This will most likely need an associated lbry/lbryschema ticket to store bookmarks in a db. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by btzr-io** [comment]
<img width=500 src="https://user-images.githubusercontent.com/14793624/30876069-b0801800-a2b2-11e7-80d1-bd75b0671313.gif">

Yep, that was me: https://github.com/lbryio/lbry-app/tree/btzr/new
I'm working on other stuff, so I'll try next week :stuck_out_tongue:

**Comment by kauffj** [comment]
@btzr-io can we discuss that feature a bit before you do much more work on it?

**Comment by btzr-io** [comment]
> Claim and channel pages would require an "Add to Bookmarks" 

I think channels should be handle on `Subscriptions` https://github.com/lbryio/lbry-app/issues/715

**Comment by btzr-io** [comment]
### Todo
- [ ]  `Add to Bookmarks` button with a dropdown the ability to create a new list or add to existing one.
- [ ] Default List: `favorites`
- [ ] Export / import bookmarks list [ ? ]

**Comment by jeff-hykin** [comment]
This is a killer feature for switching from YouTube, at least for me. I use it to que additional videos while a video is playing.

If time permits me to learn the codebase, I have the background for helping with a PR. Guidance/status update on this issue would be helpful.

I just found lbry today. The fact that I can find this issue for a feature (instead of submitting feedback to who-knows-where) is fantastic. The Agile workflow is also great to see.

**Comment by seanyesmunt** [comment]
Hey @jeff-hykin !

This feature is on hold until we have a plan for playlists
https://github.com/lbryio/lbry-desktop/issues/1982

Once we have a way to build proper playlists, then it will be simple to create a new "watch later" playlist.

**Comment by kauffj** [comment]
If @jeff-hykin wants to work on this, IMO there'd be no problem with storing watch later in your local settings (ideally wallet) to start. While we do need to build out playlists generally, proper playlists will require spending LBC (even if a small amount), since it is a publish.

I'm not sure watch later should work that way. So if a first version was just a button/element that pushed to local wallet state (this way it propagates) and that added the corresponding list to a tab in your Library, I think that could make sense...

**Comment by jeff-hykin** [comment]
@seanyesmunt that's great to hear! Thanks for the update.

**Comment by jeff-hykin** [comment]
@kauffj LocalStorage on the web would be a breeze to implement on my side. I'm not sure how that would work with your mobile software stack, and I'll have to get more familiar with the wallet.

It's just a "play next" buffer that would take priority over the existing autoplay, so temporary storage would work fine. I only use the YouTube "watch later" playlist as a makeshift solution. The most common situation is when two or more of the related videos seem interesting, but I don't want to have to manually perform a backtracking depth-first search process to eventually reach the second video.

If playlists were already implemented it would make sense to reuse that logic, especially for removing and changing the order of videos in the que. As a standalone feature though the logic should still be relatively simple.

**Comment by seanyesmunt** [comment]
@jeff-hykin we already have a (semi-broken atm) system in place to sync data between devices. All you need to do is add it to the redux store, then add that key in a few other places.

Maybe you could start by creating a `watchLater` reducer? It would just need to store a list of lbry URLs, and would need actions to add to the end of the list, and remove from the front of the list.

**Comment by derycck** [comment]
A small and improvised suggestion on one of the ways to enable synchronization of these 'Bookmarking / Watch later lists' between different devices (desktop, mobile), would be to offer the user the possibility of defining a folder on their device to 'dump' the data they support this 'bookmarking / watch later lits' function.
Thus, the user is responsible for informing a folder that is being monitored by a synchronization service, such as the dropbox.
This type of 'freedom' and 'low-coupling' of synchronizing settings in apps, has already been implemented, for example, in the settings of the notepad ++ text editor.

that serves merely as another possibility at the table :)

**Comment by apenasrr** [comment]
A small and improvised suggestion on one of the ways to enable synchronization of these 'Bookmarking / Watch later lists' between different devices (desktop, mobile), would be to offer the user the possibility of defining a folder on their device to 'dump' the data they support this 'bookmarking / watch later lits' function.
Thus, the user is responsible for informing a folder that is being monitored by a synchronization service, such as the dropbox.
This type of 'freedom' and 'low-coupling' of synchronizing settings in apps, has already been implemented, for example, in the settings of the notepad ++ text editor.

that serves merely as another possibility at the table :)
