### ISSUE TITLE
UI overhaul

### ISSUE THREAD

**Issue by locriacyber** [lbryio/lbry-desktop#7272]
Currently, LBRY's UI is hard to use due to various reasons. We do a lot better by learning from existing video viewing platforms.

## Example: Home Page

**Youtube**
![Youtube](https://user-images.githubusercontent.com/74560659/140629068-d642cbf9-ed43-403c-9474-0f7834408423.png)

**LBRY**: too many buttons at first glance. Also, navigation (back/forward) shouldn't be part of the UI.
![LBRY](https://user-images.githubusercontent.com/74560659/140629067-5f8f0914-3fd8-4008-aa15-23965a4fd0db.png)

## Roadmap
- [ ] redesign home page
  - [ ] reduce number of buttons
- [ ] add tabs and navigation. LBRY-desktop uses a browser anyways, so why not allow opening multiple videos at once?
- other UI issues (feel free to mention this issue in other issues for backlinks)

**Comment by locriacyber** [comment]
Probably should make this a Github Project, but seems like it's disabled for this repo.

**Comment by Odyssey346** [comment]
> LBRY: too many buttons at first glance. Also, navigation (back/forward) shouldn't be part of the UI.
How are people supposed to go back/forward then? This is a desktop app, and the only other way would be to use keyboard shortcuts which not everybody uses.

**Comment by locriacyber** [comment]
> > LBRY: too many buttons at first glance. Also, navigation (back/forward) shouldn't be part of the UI.
> 
> How are people supposed to go back/forward then? This is a desktop app, and the only other way would be to use keyboard shortcuts which not everybody uses.

Expose browser tabs and back/forward buttons that way. The desktop app is a browser but without the usual browser UI.

**Comment by Odyssey346** [comment]
I see.

Den 23. november 2021 06:57:05 CET, skrev locriacyber ***@***.***>:
